[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "mkg5599",email = "gummadm@oregonstate.edu"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi (>=0.116.1,<0.117.0)",
    "python-multipart (>=0.0.20,<0.0.21)",
    "openai (>=1.25.0)",
    "python-dotenv (>=1.0.1)",
    "PyYAML (>=6.0)"
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
uvicorn = ">=0.35.0,<0.36.0"
ruff = ">=0.5.5,<0.6.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"